import logging

from homeassistant.helpers.entity import EntityCategory

DOMAIN = "epever_hi"
CONF_SLAVE = "slave"

LOGGER = logging.getLogger(__package__)

# EPEVER Hi Solar Charge Controller Register Definitions
# Based on EPEVER Hi Modbus Protocol Documentation

SENSOR_DEFINITIONS_NEW = {
    0x3100: {
        "key": "solar_voltage",
        "name": "Solar Panel Voltage",
        "unit": "V",
        "scale": 0.01,
        "precision": 2,
        "device_class": "voltage",
        "readable": True,
    },
    0x3101: {
        "key": "solar_current",
        "name": "Solar Panel Current",
        "unit": "A",
        "scale": 0.01,
        "precision": 2,
        "device_class": "current",
        "readable": True,
    },
    0x3102: {
        "key": "solar_power_low",
        "name": "Solar Panel Power Low",
        "unit": "W",
        "scale": 0.01,
        "precision": 2,
        "device_class": "power",
        "readable": True,
    },
    0x3103: {
        "key": "solar_power_high",
        "name": "Solar Panel Power High",
        "unit": "W",
        "scale": 0.01,
        "precision": 2,
        "device_class": "power",
        "readable": True,
    },
    0x3104: {
        "key": "battery_voltage",
        "name": "Battery Voltage",
        "unit": "V",
        "scale": 0.01,
        "precision": 2,
        "device_class": "voltage",
        "readable": True,
    },
    0x3105: {
        "key": "battery_current",
        "name": "Battery Current",
        "unit": "A",
        "scale": 0.01,
        "precision": 2,
        "device_class": "current",
        "readable": True,
    },
    0x3106: {
        "key": "battery_power_low",
        "name": "Battery Power Low",
        "unit": "W",
        "scale": 0.01,
        "precision": 2,
        "device_class": "power",
        "readable": True,
    },
    0x3107: {
        "key": "battery_power_high",
        "name": "Battery Power High",
        "unit": "W",
        "scale": 0.01,
        "precision": 2,
        "device_class": "power",
        "readable": True,
    },
    0x3108: {
        "key": "load_voltage",
        "name": "Load Voltage",
        "unit": "V",
        "scale": 0.01,
        "precision": 2,
        "device_class": "voltage",
        "readable": True,
    },
    0x3109: {
        "key": "load_current",
        "name": "Load Current",
        "unit": "A",
        "scale": 0.01,
        "precision": 2,
        "device_class": "current",
        "readable": True,
    },
    0x310A: {
        "key": "load_power_low",
        "name": "Load Power Low",
        "unit": "W",
        "scale": 0.01,
        "precision": 2,
        "device_class": "power",
        "readable": True,
    },
    0x310B: {
        "key": "load_power_high",
        "name": "Load Power High",
        "unit": "W",
        "scale": 0.01,
        "precision": 2,
        "device_class": "power",
        "readable": True,
    },
    0x310C: {
        "key": "battery_temperature",
        "name": "Battery Temperature",
        "unit": "°C",
        "scale": 0.01,
        "precision": 1,
        "device_class": "temperature",
        "readable": True,
    },
    0x310D: {
        "key": "device_temperature",
        "name": "Device Temperature",
        "unit": "°C",
        "scale": 0.01,
        "precision": 1,
        "device_class": "temperature",
        "readable": True,
    },
    0x310E: {
        "key": "battery_soc",
        "name": "Battery SOC",
        "unit": "%",
        "scale": 1,
        "precision": 0,
        "device_class": "battery",
        "readable": True,
    },
    0x310F: {
        "key": "remote_temperature",
        "name": "Remote Battery Temperature",
        "unit": "°C",
        "scale": 0.01,
        "precision": 1,
        "device_class": "temperature",
        "readable": True,
    },
    0x3110: {
        "key": "battery_real_voltage",
        "name": "Battery Real Rated Voltage",
        "unit": "V",
        "scale": 0.01,
        "precision": 2,
        "device_class": "voltage",
        "readable": True,
    },
}


REGISTER_DEFINITIONS = {
    # Battery Settings
    0x9000: {
        "key": "battery_type",
        "name": "Battery Type",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "min": 1,
        "max": 7,
        "readable": True,
        "writable": True,
    },
    0x9001: {
        "key": "battery_capacity",
        "name": "Battery Capacity",
        "unit": "Ah",
        "scale": 1,
        "precision": 0,
        "min": 1,
        "max": 1000,
        "readable": True,
        "writable": True,
    },
    0x9002: {
        "key": "temperature_compensation_coeff",
        "name": "Temperature Compensation Coefficient",
        "unit": "mV/°C/2V",
        "scale": 1,
        "precision": 0,
        "min": 0,
        "max": 9,
        "readable": True,
        "writable": True,
    },
    0x9003: {
        "key": "high_volt_disconnect",
        "name": "High Voltage Disconnect",
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.01,
        "precision": 2,
        "min": 9,
        "max": 17,
        "readable": True,
        "writable": True,
    },
    0x9004: {
        "key": "charging_limit_voltage",
        "name": "Charging Limit Voltage",
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.01,
        "precision": 2,
        "min": 9,
        "max": 17,
        "readable": True,
        "writable": True,
    },
    0x9005: {
        "key": "over_voltage_reconnect",
        "name": "Over Voltage Reconnect",
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.01,
        "precision": 2,
        "min": 9,
        "max": 17,
        "readable": True,
        "writable": True,
    },
    0x9006: {
        "key": "equalization_voltage",
        "name": "Equalization Voltage",
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.01,
        "precision": 2,
        "min": 9,
        "max": 17,
        "readable": True,
        "writable": True,
    },
    0x9007: {
        "key": "boost_voltage",
        "name": "Boost Voltage",
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.01,
        "precision": 2,
        "min": 9,
        "max": 17,
        "readable": True,
        "writable": True,
    },
    0x9008: {
        "key": "float_voltage",
        "name": "Float Voltage",
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.01,
        "precision": 2,
        "min": 9,
        "max": 17,
        "readable": True,
        "writable": True,
    },
    0x9009: {
        "key": "boost_reconnect_voltage",
        "name": "Boost Reconnect Voltage",
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.01,
        "precision": 2,
        "min": 9,
        "max": 17,
        "readable": True,
        "writable": True,
    },
    0x900A: {
        "key": "low_voltage_reconnect",
        "name": "Low Voltage Reconnect",
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.01,
        "precision": 2,
        "min": 9,
        "max": 17,
        "readable": True,
        "writable": True,
    },
    0x900B: {
        "key": "under_voltage_recover",
        "name": "Under Voltage Recover",
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.01,
        "precision": 2,
        "min": 9,
        "max": 17,
        "readable": True,
        "writable": True,
    },
    0x900C: {
        "key": "under_voltage_warning",
        "name": "Under Voltage Warning",
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.01,
        "precision": 2,
        "min": 9,
        "max": 17,
        "readable": True,
        "writable": True,
    },
    0x900D: {
        "key": "low_voltage_disconnect",
        "name": "Low Voltage Disconnect",
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.01,
        "precision": 2,
        "min": 9,
        "max": 17,
        "readable": True,
        "writable": True,
    },
    0x900E: {
        "key": "discharging_limit_voltage",
        "name": "Discharging Limit Voltage",
        "unit": "V",
        "device_class": "voltage",
        "scale": 0.01,
        "precision": 2,
        "min": 9,
        "max": 17,
        "readable": True,
        "writable": True,
    },
}

SWITCH_DEFINITIONS = {
    0x0002: {
        "key": "manual_control_load",
        "name": "Manual Control Load",
        "unit": "",
        "device_class": "switch",
        "readable": True,
        "writable": True,
        "entity_type": "switch",
    },
    0x0005: {
        "key": "enable_load_test",
        "name": "Enable Load Test",
        "unit": "",
        "device_class": "switch",
        "readable": True,
        "writable": True,
        "entity_type": "switch",
    },
}

BUTTON_DEFINITIONS = {
    0x0001: {
        "key": "reset_charging_parameters",
        "name": "Reset Charging Parameters",
        "unit": "",
        "device_class": "restart",
        "readable": True,
        "writable": True,
        "entity_type": "button",
    },
    0x0003: {
        "key": "force_load_on",
        "name": "Force Load On",
        "unit": "",
        "device_class": "restart",
        "readable": True,
        "writable": True,
        "entity_type": "button",
    },
    0x0004: {
        "key": "force_load_off",
        "name": "Force Load Off",
        "unit": "",
        "device_class": "restart",
        "readable": True,
        "writable": True,
        "entity_type": "button",
    },
}

# Number definitions, generated from REGISTER_DEFINITIONS
NUMBER_DEFINITIONS = [
    {
        "address": addr,
        "key": reg["key"],
        "name": reg["name"],
        "min": reg.get("min", 0),
        "max": reg.get("max", 0),
        "unit": reg.get("unit", ""),
        "scale": reg.get("scale", 1),
        "precision": reg.get("precision", 0),
        "unique_id": f"epever_hi_number_{reg['key']}",
    }
    for addr, reg in REGISTER_DEFINITIONS.items()
    if reg.get("writable")
]

# Select definitions for EPEVER Hi
SELECT_DEFINITIONS = {
    0x9000: {
        "key": "battery_type",
        "name": "Battery Type",
        "type": "uns16",
        "dataLength": 1,
        "readable": True,
        "writable": True,
        "options": {
            1: "User Defined",
            2: "Sealed",
            3: "GEL",
            4: "Flooded",
            5: "LiFePO4",
            6: "LiTernary",
            7: "LiTi",
        },
    },
}

# Diagnostic definitions for binary sensors
DIAGNOSTIC_DEFINITIONS = {
    0x3200: {
        "type": "uint16",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "bits": {
            0: {"key": "charging", "name": "Charging"},
            1: {"key": "charging_mppt", "name": "Charging MPPT"},
            2: {"key": "charging_equalizing", "name": "Charging Equalizing"},
            3: {"key": "charging_boost", "name": "Charging Boost"},
            4: {"key": "charging_float", "name": "Charging Float"},
            5: {
                "key": "charging_current_limiting",
                "name": "Charging Current Limiting",
            },
        },
    },
    0x3201: {
        "type": "uint16",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "bits": {
            0: {"key": "load_on", "name": "Load On"},
            1: {"key": "load_short_circuit", "name": "Load Short Circuit"},
            2: {"key": "load_overload", "name": "Load Overload"},
            3: {"key": "load_over_discharge", "name": "Load Over Discharge"},
            4: {"key": "input_over_current", "name": "Input Over Current"},
            5: {"key": "load_over_current", "name": "Load Over Current"},
            6: {"key": "battery_over_discharge", "name": "Battery Over Discharge"},
            7: {"key": "battery_over_voltage", "name": "Battery Over Voltage"},
            8: {
                "key": "battery_under_voltage_warning",
                "name": "Battery Under Voltage Warning",
            },
        },
    },
}

FIRMWARE_INFO = {
    0x9013: {
        "key": "device_serial_number",
        "name": "Serial Number",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "type": "char",
        "dataLength": 8,
        "readable": True,
        "writable": False,
    },
    0x900C: {
        "key": "controller_model",
        "name": "Controller Model",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "type": "uns16",
        "dataLength": 2,
        "readable": True,
        "writable": False,
    },
    0x9014: {
        "key": "firmware_version",
        "name": "Firmware Version",
        "unit": "",
        "scale": 1,
        "precision": 0,
        "type": "uns16",
        "dataLength": 2,
        "readable": True,
        "writable": False,
    },
}


def get_device_info(entry_id: str):
    return {
        "identifiers": {(DOMAIN, entry_id)},
        "name": "EPEVER Hi Solar Charge Controller",
        "manufacturer": "EPEVER",
        "model": "Hi Series",
    }
