name: Release workflow

on:
  release:
    types:
      - published

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Get release version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: Validate data
        run: |
          manifestversion=$(jq -r '.version' ${{ github.workspace }}/custom_components/epever_hi/manifest.json)
          if [ "$manifestversion" != "${{ steps.version.outputs.version }}" ]; then
            echo "The version in custom_components/epever_hi/manifest.json was not correct"
            echo "$manifestversion"
            exit 1
          fi

      - name: Create zip file for the integration
        run: |
          cd "${{ github.workspace }}/custom_components/epever_hi"
          zip epever_hi.zip -r ./

      - name: Upload the zipfile as a release asset
        uses: softprops/action-gh-release@v2.3.3
        with:
          files: ${{ github.workspace }}/custom_components/epever_hi/epever_hi.zip
